# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c0b7a8a0d36368b4ff951015787437ad3156a359b44cb6a38977a16df6b6a5f819de6c2aa4cbecf16b47b98e5f282b599e1963eb37c4ce200ed94df7ab95331

test:
  secret_key_base: 8c1dec7c74217c637d653c5733b38e9d1173071ccf692031ea0c750f9601df94b46f7a04aff949754bcbc96410e059423d40f47c4cc81a2c5b973872963ad1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
